name: text_expressions
version: 1.0.1
description: >-
  A tiny, simple and complete tool to supercharge your string files
  with dynamically-parsed expressions
author: Dorian Oszczęda <vxern@wordcollector.co.uk>
homepage: https://pub.dev/packages/text_expressions
repository: https://github.com/vxern/text_expressions
#documentation:
issue_tracker: https://github.com/vxern/text_expressions/issues

publish_to: https://pub.dev

environment:
  sdk: '>=2.13.3 <3.0.0'

dependencies:
  enum_to_string: ^2.0.1
  sprint: ^1.0.1